FROM ubuntu:18.04

# Install Sensu
RUN apt update && apt install -y ca-certificates gnupg2 netcat iputils-ping && apt clean
RUN echo "deb     https://sensu.global.ssl.fastly.net/apt bionic main" | tee /etc/apt/sources.list.d/sensu.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A20F259AEB9C94BB
RUN apt update && apt install sensu && apt clean

# Cleanup
RUN rm -rf /opt/sensu/embedded/lib/ruby/gems/2.4.0/{cache,doc}/* &&\
    find /opt/sensu/embedded/lib/ruby/gems/ -name "*.o" -delete

# Runtime Config
ENV CLIENT_SUBSCRIPTIONS=all,default \
    CLIENT_BIND=127.0.0.1 \
    CLIENT_DEREGISTER=true \
    # Transport & datastore
    TRANSPORT_NAME=redis \
    RABBITMQ_PORT=5672 \
    RABBITMQ_HOST=rabbitmq \
    RABBITMQ_USER=guest \
    RABBITMQ_PASSWORD=guest \
    RABBITMQ_VHOST=/ \
    RABBITMQ_PREFETCH=1 \
    RABBITMQ_SSL_SUPPORT=false \
    RABBITMQ_SSL_CERT='' \
    RABBITMQ_SSL_KEY='' \
    REDIS_HOST=redis \
    REDIS_PORT=6379 \
    REDIS_DB=0 \
    REDIS_AUTO_RECONNECT=true \
    REDIS_RECONNECT_ON_ERROR=false \
    # Common config
    LOG_LEVEL=debug \
    CONFIG_FILE=/etc/sensu/config.json \
    CONFIG_DIR=/etc/sensu/conf.d \
    CHECK_DIR=/etc/sensu/check.d \
    EXTENSION_DIR=/etc/sensu/extensions \
    PLUGINS_DIR=/etc/sensu/plugins \
    HANDLERS_DIR=/etc/sensu/handlers \
    # Config for gathering host metrics
    HOST_DEV_DIR=/dev \
    HOST_PROC_DIR=/proc \
    HOST_SYS_DIR=/sys \
    # Include Sensu installation embedded bin in path
    PATH=/opt/sensu/embedded/bin:$PATH \
    # -W0 avoids Sensu process output to be spoiled with ruby 2.4 warnings
    RUBYOPT=-W0

EXPOSE 3030
EXPOSE 3031
EXPOSE 4567

VOLUME ["/etc/sensu/conf.d"]

CMD ["/opt/sensu/bin/sensu-server"]
